import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./theme.config.css";
import '@radix-ui/themes/styles.css';
import Navbar from "@/components/Navbar";
import { Theme } from '@radix-ui/themes';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme appearance='dark' accentColor="iris" grayColor="slate" radius="large">
          <Navbar />
          <div className="p-5">
            {children}
          </div>
        </Theme>
      </body>
    </html>
  );
}
